name: CI Workflow

on:
  push:
    branches:
      - feature/ci-wokflow
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.get_tag.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get next version tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --match '0.0.*' --abbrev=0 2>/dev/null || echo "0.0.0")
          IFS='.' read -r -a version_parts <<< "$latest_tag"
          patch=${version_parts[2]}
          new_patch=$((patch + 1))
          new_tag="0.0.$new_patch"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

  build_and_push:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: felipeacezar/hello-world:${{ needs.tag.outputs.new_tag }}
          build-args: NO_CACHE=true
