name: Update Tag Workflow

on:
  workflow_dispatch:
    inputs:
      new_tag:
        description: 'New Docker tag'
        required: true
        type: string

jobs:
  update_manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update deployment.yaml with new tag
        run: |
          sed -i "s|image: felipeacezar/hello-world:.*|image: felipeacezar/hello-world:${{ inputs.new_tag }}|" ./apps/base/deployment.yaml
          git add ./apps/base/deployment.yaml
          git commit -m "Update image tag to ${{ inputs.new_tag }} [skip ci]" || echo "No changes"
          git push

      - name: Create and push new Git tag
        run: |
          git tag ${{ inputs.new_tag }}
          git push origin ${{ inputs.new_tag }}
